var JsDiff = require('diff');
var _ = require('lodash');

//var PATCH = "@@ -2,6 +2,10 @@\n All notable changes to this project will be documented in this file.\n This project adheres to [Semantic Versioning](http://semver.org/).\n \n+## 2.6.7\n+- Fix bug with filenames including spaces\n+- Add Turkish and Catalan translations\n+\n ## 2.6.6\n - Fix custom CSS that are generated by plugins for PDF output\n ";

var PATCH = "@@ -8,7 +8,7 @@ GitBook\n \n GitBook is a command line tool (and Node.js library) for building beautiful books using GitHub/Git and Markdown (or AsciiDoc). Here is an example: [Learn Javascript](https://www.gitbook.com/book/GitBookIO/javascript).\n \n-You can publish and host book easily online using [gitbook.com](https://www.gitbook.com). A desktop editor is [also available](https://www.gitbook.com/editor).\n+You can publish and host books easily online using [gitbook.com](https://www.gitbook.com). A desktop editor is [also available](https://www.gitbook.com/editor).\n \n Check out the [GitBook Community Slack Channel](https://slack.gitbook.com), Stay updated by following [@GitBookIO](https://twitter.com/GitBookIO) on Twitter or [GitBook](https://www.facebook.com/gitbookcom) on Facebook.\n ";


// Convert a hunk into a {before,after} object
function splitHunk(hunk) {
    var newHunk = {
        oldStart: hunk.oldStart,
        oldLines: hunk.oldLines,
        newStart: hunk.newStart,
        newLines: hunk.newLines,
        before: '',
        after: ''
    };

    _.each(hunk.lines, function(line) {
        var lineContent = line.slice(1);
        var lineType = line[0];

        if (lineType == '+') {
            newHunk.after += lineContent + '\n';
        } else if (lineType == '-') {
            newHunk.before += lineContent + '\n';
        } else {
            newHunk.before += lineContent + '\n';
            newHunk.after += lineContent + '\n';
        }
    });

    return newHunk;
}

// Convert a hunk to a patch sring
function hunkToPatchString(hunk, options) {
    var changes = JsDiff.diffWords(hunk.before, hunk.after);
    var patch = '@@ -' + hunk.oldStart + ',' + hunk.oldLines+' +' + hunk.newStart + ',' + hunk.newLines + ' @@\n';

    _.each(changes, function(change) {
        if (change.added) {
            patch = patch + options.added.replace('%s', change.value);
        } else if (change.removed) {
            patch = patch + options.removed.replace('%s', change.value);
        } else {
            patch = patch + change.value;
        }
    })

    return patch;
}

// Convert a line-diff patch to a word-diff patch
function convertToWordDiff(patch, options) {
    options = _.defaults(options || {}, {
        added: '{+%s+}',
        removed: '[-%s-]'
    });


    return _.chain(patch.hunks)
        .map(function(hunk) {
            hunk = splitHunk(hunk);
            return hunkToPatchString(hunk, options);
        })
        .join('\n\n')
        .value();
}


console.log(convertToWordDiff(JsDiff.parsePatch(PATCH)[0]));
